# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: IndySoft.VidSeen
PackageVersion: 1.2.37
MinimumOSVersion: 10.0.17763.0
InstallerType: exe
Scope: user
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --installto "<INSTALLPATH>"
  Log: --log "<LOGPATH>"
UpgradeBehavior: install
ProductCode: VidSeen
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- ProductCode: VidSeen
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\VidSeen'
Installers:
- Architecture: x64
  InstallerUrl: https://indyvidsrecordings.blob.core.windows.net/releases/win/1.2.37/VidSeen-win-x64-Setup.exe
  InstallerSha256: 4C3EAD8BBE168C096EBCC6A5EA04BDE0399725A93D322CFA73D1F84AC3FC57F5
- Architecture: arm64
  InstallerUrl: https://indyvidsrecordings.blob.core.windows.net/releases/win/1.2.37/VidSeen-win-arm64-Setup.exe
  InstallerSha256: 2C704586B630F189D0F8041944150D4AFECF63A86BC092BAEE4B0F38A804BAB2
ManifestType: installer
ManifestVersion: 1.12.0
